server:
  port: 8888
  max-http-header-size: 1024000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_eye?serverTimezone=GMT
    username: root
    password: 123123
  #    url: jdbc:h2:file:~/kibana-login/db/kibana
  #    username: admin
  #    password: 123456
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: es-eye
  profiles:
    active: dev
application:
  formatted-version: 1.2.0

management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ["httptrace", "metrics", "env", "logfile", "health"]
logging:
  config: classpath:logback-spring.xml

---
# 开发环境
ke:
  es:
    url: http://ES地址/
  version: development
  host: 127.0.0.1
  file:
    url: D:/kibana-eye/upload/
spring:
  profiles: dev

---
# 生产环境
ke:
  es:
    url: http://ES地址/
  version: product
  host: 上线后的服务器地址
  file:
    url: /home/k12app/kibana-eye/upload/
spring:
  profiles: prod
