server:
  port: 8888
  max-http-header-size: 1024000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_eye?serverTimezone=GMT
    username: root
    password: 123123
  #    url: jdbc:h2:file:~/kibana-login/db/kibana
#    username: admin
#    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: es-eye
application:
  formatted-version: 1.0.1

management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  config: classpath:logback-spring.xml